version: '3'
services:
  web:
    image: rest-section6 
    ports:
     - "4000:5000"
    environment:
     - DATABASE_URL=postgresql://postgres:docker@BDS-208-71:5432/postgres
  database:
    image: postgres
    ports:
     - "5432:5432"
    volumes:
     - /home/spencer/postgres_data:/var/lib/postgresql/data 
    environment:
     - POSTGRES_PASSWORD=docker

